#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# link all the files in dotfiles to their correct locations
mkdir -p $HOME/.config

# home bin/scripts
rm -r $HOME/bin
ln -s $DIR/bin $HOME/bin

# emacs
if [ ! -d $HOME/.emacs.d ]; then
  git clone --recursive http://github.com/syl20bnr/spacemacs ~/.emacs.d
fi
mkdir -p $DIR/.emacs.d/private
rm -r $HOME/.emacs.d/private/oppenlander
ln -s $DIR/spacemacs/private/oppenlander $HOME/.emacs.d/private/oppenlander
rm $HOME/.spacemacs
ln -s $DIR/spacemacs/spacemacs $HOME/.spacemacs

# Fish shell
rm -r $HOME/.config/fish
ln -s $DIR/fish $HOME/.config/fish

# i3wm
rm -r $HOME/.config/i3
ln -s $DIR/i3 $HOME/.config/i3

# profile
rm $HOME/.profile
ln -s $DIR/profile $HOME/.profile

# git
rm $HOME/.gitconfig
ln -s $DIR/git/gitconfig $HOME/.gitconfig
rm $HOME/.gitignore
ln -s $DIR/git/gitignore $HOME/.gitignore

# terminator
rm -r $HOME/.config/terminator
ln -s $DIR/terminator $HOME/.config/terminator

# nodejs
rm $HOME/.npmrc
ln -s $DIR/node/npmrc $HOME/.npmrc

# gtk
mkdir -p $HOME/.config/gtk-3.0
rm $HOME/.config/gtk-3.0/settings.ini
ln -s $DIR/gtk/settings.ini $HOME/.config/gtk-3.0/settings.ini
rm $HOME/.gtkrc-2.0
ln -s $DIR/gtk/gktrc-2.0 $HOME/.gtkrc-2.0
rm $HOME/.gtkrc-2.0-kde4
ln -s $DIR/gtk/gktrc-2.0-kde4 $HOME/.gtkrc-2.0-kde4

# tmux
rm $HOME/.tmux.conf
ln -s $DIR/tmux/tmux.conf $HOME/.tmux.conf
rm -r $HOME/.tmux
mkdir $HOME/.tmux
ln -s $DIR/tmux/plugins $HOME/.tmux/plugins

# xfce4
mkdir -p $HOME/.config/xfce4
mkdir -p $HOME/.config/xfce4/terminal
rm $HOME/.config/xfce4/terminal/terminalrc
ln -s $DIR/xfce4/terminalrc $HOME/.config/xfce4/terminal/terminalrc

# vim
rm -r $HOME/.vim
ln -s $DIR/vim $HOME/.vim
