#!/usr/bin/env bash

# Fish
chsh -s /usr/bin/fish

# Node.js
sudo aura -S --needed nodejs
npm i -g --python=python2 tern grunt bower
git clone https://github.com/creationix/nvm.git ~/.nvm && cd ~/.nvm && git checkout `git describe --abbrev=0 --tags` && cd -

# Install go dependencies
sudo aura -S --needed go mercurial subversion
go get -u github.com/nsf/gocode
go get -u github.com/jstemmer/gotags
go get -u github.com/golang/lint/golint
go get -u code.google.com/p/go.tools/cmd/oracle
go get -u code.google.com/p/rog-go/exp/cmd/godef
go get -u github.com/kisielk/errcheck
go get -u github.com/bradfitz/goimports
