#!/usr/bin/env bash

# Node.js
sudo aura -S nodejs
npm i -g --python=python2 tern grunt bower

# Install go dependencies
sudo aura -S go
go get -u github.com/nsf/gocode
go get -u github.com/jstemmer/gotags
go get -u github.com/golang/lint/golint
go get -u code.google.com/p/go.tools/cmd/oracle
go get -u code.google.com/p/rog-go/exp/cmd/godef
go get -u github.com/kisielk/errcheck
go get -u github.com/bradfitz/goimports
