#!/usr/bin/env bash
# Installs (most of) my Arch Linux setup
# Assumes user account/sudo has been set up, and an internet connection.

# Ensure the system is up to date
sudo pacman -Syu

hash pacaur &> /dev/null
if [ $? -eq 1 ]; then
    # Install base packages we'll need for pacaur
    sudo pacman -S git base-devel yajl openssl curl expac

    # Enter temp folder to install cower/pacaur
    mkdir -p $HOME/tmp
    cd $HOME/tmp

    # Download/build/install cower
    curl -o cower.tar.gz https://aur.archlinux.org/packages/co/cower/cower.tar.gz
    tar xzf cower.tar.gz
    cd cower
    makepkg
    sudo pacman -U cower*.pkg.tar.gz
    cd ..

    # Download/build/install pacaur
    curl -o pacaur.tar.gz https://aur.archlinux.org/packages/pa/pacaur/pacaur.tar.gz
    tar xzf pacaur.tar.gz
    cd pacaur
    makepkg
    sudo pacman -U pacaur*.pkg.tar.gz
    cd ..

    # Cleanup
    rm cower.tar.gz && rm -r cower && rm pacaur.tar.gz && rm -r pacaur
    cd $HOME
fi

# Install software
pacaur -S \
    compton \
    elementary-icon-theme \
    emacs \
    dmenu2 \
    feh \
    fish \
    go \
    google-chrome \
    gtk-theme-elementary \
    i3 \
    i3blocks \
    iw \
    jdk \
    libreoffice \
    lightdm \
    lxappearance \
    lxrandr \
    pcmanfm \
    playerctl \
    skype \
    spotify \
    redshift \
    terminator \
    tmux \
    ttf-dejavu \
    ttf-font-awesome \
    xautolock \
    xfce4-mixer \
    wireless-tools \
    wpa_supplicant

# Install go dependencies
# gocode
go get -u github.com/nsf/gocode
# gotags
go get -u github.com/jstemmer/gotags
# golint
go get -u github.com/golang/lint/golint
# oracle
go get -u code.google.com/p/go.tools/cmd/oracle
# godef
go get -u code.google.com/p/rog-go/exp/cmd/godef
# errcheck
go get -u github.com/kisielk/errcheck
# goimports
go get -u github.com/bradfitz/goimports
