#!/usr/bin/env bash
# Installs (most of) my Arch Linux setup
# Assumes you are using a user account, sudo is set up, and there is an internet connection.

# Ensure the system is up to date
sudo pacman -Syu

hash aura &> /dev/null
if [ $? -eq 1 ]; then
    # Install base packages we'll need for pacaur
    sudo pacman -S git base-devel openssl curl abs gmp pcre

    # Enter temp folder to install cower/pacaur
    mkdir -p $HOME/tmp
    cd $HOME/tmp

    # Download/build/install customizepkg
    curl -o customizepkg.tar.gz https://aur.archlinux.org/packages/cu/customizepkg/customizepkg.tar.gz
    tar xzf customizepkg.tar.gz
    cd customizepkg
    makepkg
    sudo pacman -U customizepkg*.pkg.tar.gz
    cd ..

    # Download/build/install aura
    curl -o aura-bin.tar.gz https://aur.archlinux.org/packages/au/aura-bin/aura-bin.tar.gz
    tar xzf aura-bin.tar.gz
    cd aura-bin
    makepkg
    sudo pacman -U aura-bin*.pkg.tar.gz
    cd ..

    # Cleanup
    rm aura-bin.tar.gz && rm -r aura-bin && rm aura-bin.tar.gz && rm -r aura-bin
    cd $HOME
fi

# Install repo software
sudo aura -S --needed \
     alsa-oss \
     alsa-plugins \
     alsa-utils \
     arandr \
     elementary-icon-theme \
     emacs \
     feh \
     filezilla \
     firefox \
     gvim \
     gwenview \
     i3 \
     i3lock \
     i3status \
     ifplugd \
     iw \
     libreoffice \
     lightdm \
     lightdm-gtk3-greeter \
     lxappearance \
     lxrandr \
     net-tools \
     pavucontrol \
     pcmanfm \
     powertop \
     pulseaudio \
     pulseaudio-alsa \
     python2 \
     python2-pip \
     python-pip \
     skype \
     smplayer \
     redshift \
     terminator \
     tmux \
     ttf-dejavu \
     xautolock \
     xfce4-mixer \
     xfce4-power-manager \
     xorg \
     vlc \
     wireless_tools \
     wpa_supplicant \
     xorg

# Install AUR software
sudo aura -A --needed \
     compton \
     dmenu2-underline \
     fasd \
     fish-shell-git \
     google-chrome \
     gtk-theme-elementary-bzr \
     hipchat \
     i3blocks \
     jdk \
     otf-font-awesome \
     otf-powerline-symbols-git \
     otf-source-code-pro-powerline-git \
     playerctl \
     rxvt-unicode-patched \
     silver-searcher-git \
     spotify \
     silver-searcher-git \
     ttf-font-awesome \
     ttf-google-fonts-git \
     zeal-git
