 local menue0e4fc6213e8b3593495a7260c3a4c2e = {
     {"Jovie", "jovie"},
     {"KMag", "kmag -caption KMag ", "/usr/share/icons/hicolor/16x16/apps/kmag.png" },
     {"KMouseTool", "kmousetool -caption KMouseTool ", "/usr/share/icons/hicolor/16x16/apps/kmousetool.png" },
     {"KMouth", "kmouth -caption KMouth ", "/usr/share/icons/hicolor/16x16/apps/kmouth.png" },
 }

 local menu98edb85b00d9527ad5acebe451b3fae6 = {
     {"Akonaditray", "akonaditray", "/usr/share/icons/hicolor/22x22/apps/akonaditray.png" },
     {"Ark", "ark -caption Ark ", "/usr/share/icons/hicolor/16x16/apps/ark.png" },
     {"Filelight", "filelight ", "/usr/share/icons/hicolor/16x16/apps/filelight.png" },
     {"Jovie", "jovie"},
     {"KAlarm", "kalarm -caption KAlarm ", "/usr/share/icons/hicolor/16x16/apps/kalarm.png" },
     {"KCalc", "kcalc -caption KCalc"},
     {"KCharSelect", "kcharselect -caption KCharSelect"},
     {"KFileReplace", "kfilereplace  -caption KFileReplace", "/usr/share/icons/hicolor/22x22/apps/kfilereplace.png" },
     {"KFloppy", "kfloppy -caption KFloppy", "/usr/share/icons/hicolor/16x16/apps/kfloppy.png" },
     {"KGpg", "kgpg ", "/usr/share/icons/hicolor/16x16/apps/kgpg.png" },
     {"KJots", "kjots -caption KJots", "/usr/share/icons/hicolor/16x16/apps/kjots.png" },
     {"KMag", "kmag -caption KMag ", "/usr/share/icons/hicolor/16x16/apps/kmag.png" },
     {"KMail Import Wizard", "importwizard", "/usr/share/icons/hicolor/64x64/apps/kontact-import-wizard.png" },
     {"KMouseTool", "kmousetool -caption KMouseTool ", "/usr/share/icons/hicolor/16x16/apps/kmousetool.png" },
     {"KMouth", "kmouth -caption KMouth ", "/usr/share/icons/hicolor/16x16/apps/kmouth.png" },
     {"KNotes", "knotes", "/usr/share/icons/hicolor/16x16/apps/knotes.png" },
     {"KTeaTime", "kteatime", "/usr/share/icons/hicolor/16x16/apps/kteatime.png" },
     {"KTimeTracker", "ktimetracker", "/usr/share/icons/hicolor/16x16/apps/ktimetracker.png" },
     {"KTimer", "ktimer", "/usr/share/icons/hicolor/16x16/apps/ktimer.png" },
     {"KWrite", "kwrite "},
     {"Kate", "kate -b ", "/usr/share/icons/hicolor/16x16/apps/kate.png" },
     {"Kleopatra", "kleopatra", "/usr/share/icons/hicolor/16x16/apps/kleopatra.png" },
     {"Okteta", "okteta -caption Okteta ", "/usr/share/icons/hicolor/16x16/apps/okteta.png" },
     {"Sweeper", "sweeper"},
     {"Synergy", "synergy", "///usr/share/icons/synergy.ico" },
     {"Vi IMproved", "gvim -f ", "/usr/share/pixmaps/gvim.png" },
 }

 local menude7a22a0c94aa64ba2449e520aa20c99 = {
     {"Artikulate", "artikulate -caption Artikulate ", "/usr/share/icons/hicolor/16x16/apps/artikulate.png" },
     {"Avogadro", "avogadro ", "/usr/share/pixmaps/avogadro-icon.png" },
     {"Blinken", "blinken", "/usr/share/icons/hicolor/16x16/apps/blinken.png" },
     {"Cantor", "cantor  -caption Cantor", "/usr/share/icons/hicolor/16x16/apps/cantor.png" },
     {"KAlgebra", "kalgebra", "/usr/share/icons/hicolor/16x16/apps/kalgebra.png" },
     {"KAlgebra Mobile", "kalgebramobile", "/usr/share/icons/hicolor/16x16/apps/kalgebra.png" },
     {"KBruch", "kbruch -caption KBruch ", "/usr/share/icons/hicolor/16x16/apps/kbruch.png" },
     {"KGeography", "kgeography", "/usr/share/icons/hicolor/16x16/apps/kgeography.png" },
     {"KHangMan", "khangman -caption KHangMan ", "/usr/share/icons/hicolor/16x16/apps/khangman.png" },
     {"KLettres", "klettres -caption KLettres ", "/usr/share/icons/hicolor/16x16/apps/klettres.png" },
     {"KStars", "kstars -caption KStars ", "/usr/share/icons/hicolor/16x16/apps/kstars.png" },
     {"KTouch", "ktouch -caption KTouch ", "/usr/share/icons/hicolor/16x16/apps/ktouch.png" },
     {"KTurtle", "kturtle  -caption KTurtle", "/usr/share/icons/hicolor/16x16/apps/kturtle.png" },
     {"KWordQuiz", "kwordquiz -caption KWordQuiz ", "/usr/share/icons/hicolor/16x16/apps/kwordquiz.png" },
     {"Kalzium", "kalzium -caption Kalzium ", "/usr/share/icons/hicolor/16x16/apps/kalzium.png" },
     {"Kanagram", "kanagram", "/usr/share/icons/hicolor/16x16/apps/kanagram.png" },
     {"Kig", "kig  -caption Kig", "/usr/share/icons/hicolor/16x16/apps/kig.png" },
     {"Kiten", "kiten -caption Kiten ", "/usr/share/icons/hicolor/16x16/apps/kiten.png" },
     {"KmPlot", "kmplot", "/usr/share/icons/hicolor/16x16/apps/kmplot.png" },
     {"Marble", "marble-touch ", "/usr/share/icons/hicolor/16x16/apps/marble.png" },
     {"Marble", "marble ", "/usr/share/icons/hicolor/16x16/apps/marble.png" },
     {"Marble", "marble-mobile ", "/usr/share/icons/hicolor/16x16/apps/marble.png" },
     {"Marble", "marble-qt ", "/usr/share/icons/hicolor/16x16/apps/marble.png" },
     {"Pairs", "pairs  -caption Pairs", "/usr/share/icons/hicolor/16x16/apps/pairs.png" },
     {"Pairs Theme Editor", "pairseditor  -caption Pairs Theme Editor", "/usr/share/icons/hicolor/16x16/apps/pairseditor.png" },
     {"Parley", "parley ", "/usr/share/icons/hicolor/16x16/apps/parley.png" },
     {"Rocs", "rocs  -caption Rocs", "/usr/share/icons/hicolor/16x16/apps/rocs.png" },
     {"Step", "step -caption Step ", "/usr/share/icons/hicolor/16x16/apps/step.png" },
 }

 local menu251bd8143891238ecedc306508e29017 = {
     {"AMOR", "amor", "/usr/share/icons/hicolor/16x16/apps/amor.png" },
     {"Blinken", "blinken", "/usr/share/icons/hicolor/16x16/apps/blinken.png" },
     {"Bomber", "bomber -caption Bomber", "/usr/share/icons/hicolor/32x32/apps/bomber.png" },
     {"Bovo", "bovo -caption Bovo", "/usr/share/icons/hicolor/16x16/apps/bovo.png" },
     {"Granatier", "granatier", "/usr/share/icons/hicolor/16x16/apps/granatier.png" },
     {"KAtomic", "katomic -caption KAtomic", "/usr/share/icons/hicolor/16x16/apps/katomic.png" },
     {"KBlackBox", "kblackbox -caption KBlackBox", "/usr/share/icons/hicolor/16x16/apps/kblackbox.png" },
     {"KBlocks", "kblocks -caption KBlocks", "/usr/share/icons/hicolor/16x16/apps/kblocks.png" },
     {"KBounce", "kbounce -caption KBounce", "/usr/share/icons/hicolor/16x16/apps/kbounce.png" },
     {"KBreakOut", "kbreakout -caption KBreakOut", "/usr/share/icons/hicolor/16x16/apps/kbreakout.png" },
     {"KDiamond", "kdiamond -caption KDiamond", "/usr/share/icons/hicolor/16x16/apps/kdiamond.png" },
     {"KFourInLine", "kfourinline", "/usr/share/icons/hicolor/16x16/apps/kfourinline.png" },
     {"KGoldrunner", "kgoldrunner", "/usr/share/icons/hicolor/16x16/apps/kgoldrunner.png" },
     {"KHangMan", "khangman -caption KHangMan ", "/usr/share/icons/hicolor/16x16/apps/khangman.png" },
     {"KJumpingCube", "kjumpingcube -caption KJumpingCube", "/usr/share/icons/hicolor/16x16/apps/kjumpingcube.png" },
     {"KMahjongg", "kmahjongg -caption KMahjongg", "/usr/share/icons/hicolor/16x16/apps/kmahjongg.png" },
     {"KMines", "kmines -caption KMines", "/usr/share/icons/hicolor/16x16/apps/kmines.png" },
     {"KNetWalk", "knetwalk -caption KNetWalk", "/usr/share/icons/hicolor/16x16/apps/knetwalk.png" },
     {"KPatience", "kpat -caption KPatience", "/usr/share/icons/hicolor/16x16/apps/kpat.png" },
     {"KReversi", "kreversi -caption KReversi", "/usr/share/icons/hicolor/16x16/apps/kreversi.png" },
     {"KSnake", "ktron -snake -caption KSnake ", "/usr/share/icons/hicolor/16x16/apps/kdesnake.png" },
     {"KSnakeDuel", "ktron -caption KSnakeDuel ", "/usr/share/icons/hicolor/16x16/apps/ktron.png" },
     {"KSpaceDuel", "kspaceduel -caption KSpaceDuel", "/usr/share/icons/hicolor/16x16/apps/kspaceduel.png" },
     {"KSquares", "ksquares  -caption KSquares", "/usr/share/icons/hicolor/16x16/apps/ksquares.png" },
     {"KSudoku", "ksudoku  -caption KSudoku", "/usr/share/icons/hicolor/16x16/apps/ksudoku.png" },
     {"Kajongg", "kajongg", "/usr/share/icons/hicolor/16x16/apps/kajongg.png" },
     {"Kanagram", "kanagram", "/usr/share/icons/hicolor/16x16/apps/kanagram.png" },
     {"Kapman", "kapman", "/usr/share/icons/hicolor/16x16/apps/kapman.png" },
     {"Kigo", "kigo  -caption Kigo", "/usr/share/icons/hicolor/16x16/apps/kigo.png" },
     {"Killbots", "killbots -caption Killbots", "/usr/share/icons/hicolor/16x16/apps/killbots.png" },
     {"Kiriki", "kiriki -caption Kiriki", "/usr/share/icons/hicolor/16x16/apps/kiriki.png" },
     {"Klickety", "klickety -caption Klickety", "/usr/share/icons/hicolor/16x16/apps/klickety.png" },
     {"Kolf", "kolf ", "/usr/share/icons/hicolor/16x16/apps/kolf.png" },
     {"Kollision", "kollision", "/usr/share/icons/hicolor/16x16/apps/kollision.png" },
     {"Kolor Lines", "klines -caption Kolor Lines", "/usr/share/icons/hicolor/16x16/apps/klines.png" },
     {"Konquest", "konquest -caption Konquest", "/usr/share/icons/hicolor/16x16/apps/konquest.png" },
     {"KsirK", "ksirk -caption KsirK ", "/usr/share/icons/hicolor/16x16/apps/ksirk.png" },
     {"KsirK Skin Editor", "ksirkskineditor -caption KsirK Skin Editor "},
     {"Kubrick", "kubrick", "/usr/share/icons/hicolor/16x16/apps/kubrick.png" },
     {"LSkat", "lskat", "/usr/share/icons/hicolor/16x16/apps/lskat.png" },
     {"Naval Battle", "knavalbattle -caption Naval Battle ", "/usr/share/icons/hicolor/16x16/apps/knavalbattle.png" },
     {"Pairs", "pairs  -caption Pairs", "/usr/share/icons/hicolor/16x16/apps/pairs.png" },
     {"Pairs Theme Editor", "pairseditor  -caption Pairs Theme Editor", "/usr/share/icons/hicolor/16x16/apps/pairseditor.png" },
     {"Palapeli", "palapeli", "/usr/share/icons/hicolor/16x16/apps/palapeli.png" },
     {"Potato Guy", "ktuberling -caption Potato Guy ", "/usr/share/icons/hicolor/16x16/apps/ktuberling.png" },
     {"SameGame", "klickety --KSameMode -caption SameGame", "/usr/share/icons/hicolor/16x16/apps/ksame.png" },
     {"Shisen-Sho", "kshisen -caption Shisen-Sho", "/usr/share/icons/hicolor/16x16/apps/kshisen.png" },
     {"Steam", "/usr/bin/steam ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
     {"picmi", "picmi", "/usr/share/icons/hicolor/16x16/apps/picmi.png" },
 }

 local menud334dfcea59127bedfcdbe0a3ee7f494 = {
     {"Gwenview", "gwenview  -caption Gwenview ", "/usr/share/icons/hicolor/16x16/apps/gwenview.png" },
     {"KColorChooser", "kcolorchooser", "/usr/share/icons/hicolor/16x16/apps/kcolorchooser.png" },
     {"KRuler", "kruler", "/usr/share/icons/hicolor/16x16/apps/kruler.png" },
     {"KSnapshot", "ksnapshot -caption KSnapshot", "/usr/share/icons/hicolor/16x16/apps/ksnapshot.png" },
     {"KolourPaint", "kolourpaint ", "/usr/share/icons/hicolor/16x16/apps/kolourpaint.png" },
     {"Okular", "okular   -caption Okular", "/usr/share/icons/hicolor/16x16/apps/okular.png" },
 }

 local menuc8205c7636e728d448c2774e6a4a944b = {
     {"Akregator", "akregator  -caption Akregator", "/usr/share/icons/hicolor/16x16/apps/akregator.png" },
     {"Avahi SSH Server Browser", "/usr/bin/bssh"},
     {"Avahi VNC Server Browser", "/usr/bin/bvnc"},
     {"Blogilo", "blogilo  -caption Blogilo", "/usr/share/icons/hicolor/16x16/apps/blogilo.png" },
     {"Cloud Storage Manager", "storageservicemanager", "/usr/share/icons/hicolor/16x16/apps/kmail.png" },
     {"Contact Theme Editor", "contactthemeeditor", "/usr/share/icons/hicolor/16x16/apps/kaddressbook.png" },
     {"Dropbox", "dropboxd", "/usr/share/pixmaps/dropbox.png" },
     {"Firefox", "/usr/lib/firefox/firefox ", "/usr/share/icons/hicolor/16x16/apps/firefox.png" },
     {"Google Chrome", "/usr/bin/google-chrome-stable ", "/usr/share/icons/hicolor/16x16/apps/google-chrome.png" },
     {"HipChat", "/opt/HipChat/bin/hipchat", "/usr/share/icons/hicolor/16x16/apps/hipchat.png" },
     {"KGet", "kget -caption KGet  ", "/usr/share/icons/hicolor/16x16/apps/kget.png" },
     {"KMail", "kmail -caption KMail ", "/usr/share/icons/hicolor/16x16/apps/kmail.png" },
     {"KMail Header Theme Editor", "headerthemeeditor", "/usr/share/icons/hicolor/16x16/apps/kmail.png" },
     {"KNode", "knode -caption KNode", "/usr/share/icons/hicolor/16x16/apps/knode.png" },
     {"KPPP", "kppp", "/usr/share/icons/hicolor/16x16/apps/kppp.png" },
     {"KRDC", "krdc -caption KRDC "},
     {"KTnef", "ktnef ", "/usr/share/icons/hicolor/48x48/apps/ktnef.png" },
     {"Konqueror", "kfmclient openProfile webbrowsing", "/usr/share/icons/hicolor/16x16/apps/konqueror.png" },
     {"Kopete", "kopete -caption Kopete ", "/usr/share/icons/hicolor/16x16/apps/kopete.png" },
     {"Krfb", "krfb -caption Krfb "},
     {"Skype", "skype ", "/usr/share/icons/hicolor/16x16/apps/skype.png" },
     {"Steam", "/usr/bin/steam ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
     {"wpa_gui", "wpa_gui", "/usr/share/pixmaps/wpa_gui.svg" },
 }

 local menudf814135652a5a308fea15bff37ea284 = {
     {"Cloud Storage Manager", "storageservicemanager", "/usr/share/icons/hicolor/16x16/apps/kmail.png" },
     {"Contact Theme Editor", "contactthemeeditor", "/usr/share/icons/hicolor/16x16/apps/kaddressbook.png" },
     {"KAddressBook", "kaddressbook ", "/usr/share/icons/hicolor/16x16/apps/kaddressbook.png" },
     {"KMail", "kmail -caption KMail ", "/usr/share/icons/hicolor/16x16/apps/kmail.png" },
     {"KMail Header Theme Editor", "headerthemeeditor", "/usr/share/icons/hicolor/16x16/apps/kmail.png" },
     {"KOrganizer", "korganizer ", "/usr/share/icons/hicolor/16x16/apps/korganizer.png" },
     {"KTimeTracker", "ktimetracker", "/usr/share/icons/hicolor/16x16/apps/ktimetracker.png" },
     {"KTnef", "ktnef ", "/usr/share/icons/hicolor/48x48/apps/ktnef.png" },
     {"Kontact", "kontact", "/usr/share/icons/hicolor/16x16/apps/kontact.png" },
     {"Lokalize", "lokalize  -caption Lokalize", "/usr/share/icons/hicolor/32x32/apps/lokalize.png" },
     {"Okular", "okular   -caption Okular", "/usr/share/icons/hicolor/16x16/apps/okular.png" },
 }

 local menue6f43c40ab1c07cd29e4e83e4ef6bf85 = {
     {"Akonadi Console", "akonadiconsole", "/usr/share/icons/hicolor/16x16/apps/akonadiconsole.png" },
     {"CMake", "cmake-gui ", "/usr/share/pixmaps/CMakeSetup32.png" },
     {"Cervisia", "cervisia -caption Cervisia  ", "/usr/share/icons/hicolor/16x16/apps/cervisia.png" },
     {"Emacs", "emacs ", "/usr/share/icons/hicolor/16x16/apps/emacs.png" },
     {"Java Mission Control", "jmc", "/usr/share/icons/hicolor/16x16/apps/sun-java.png" },
     {"Java Monitoring and Management Console", "jconsole", "/usr/share/icons/hicolor/16x16/apps/sun-java.png" },
     {"Java VisualVM", "jvisualvm", "/usr/share/icons/hicolor/16x16/apps/sun-java.png" },
     {"KAppTemplate", "kapptemplate", "/usr/share/icons/hicolor/16x16/apps/kapptemplate.png" },
     {"KCachegrind", "kcachegrind -caption KCachegrind ", "/usr/share/icons/hicolor/32x32/apps/kcachegrind.png" },
     {"KImageMapEditor", "kimagemapeditor -caption KImageMapEditor ", "/usr/share/icons/hicolor/16x16/apps/kimagemapeditor.png" },
     {"KLinkStatus", "klinkstatus   -caption KLinkStatus", "/usr/share/icons/hicolor/16x16/apps/klinkstatus.png" },
     {"KUIViewer", "kuiviewer -caption KUIViewer", "/usr/share/icons/hicolor/16x16/apps/kuiviewer.png" },
     {"Kompare", "kompare -caption Kompare -o ", "/usr/share/icons/hicolor/16x16/apps/kompare.png" },
     {"Lokalize", "lokalize  -caption Lokalize", "/usr/share/icons/hicolor/32x32/apps/lokalize.png" },
     {"Qt4 Assistant ", "assistant-qt4", "/usr/share/icons/hicolor/32x32/apps/assistant-qt4.png" },
     {"Qt4 Designer", "designer-qt4", "/usr/share/icons/hicolor/128x128/apps/designer-qt4.png" },
     {"Qt4 Linguist ", "linguist-qt4", "/usr/share/icons/hicolor/16x16/apps/linguist-qt4.png" },
     {"Qt4 QDbusViewer ", "qdbusviewer-qt4", "/usr/share/icons/hicolor/32x32/apps/qdbusviewer-qt4.png" },
     {"Umbrello", "umbrello -caption Umbrello", "/usr/share/icons/hicolor/16x16/apps/umbrello.png" },
     {"Zeal", "zeal", "/usr/share/icons/hicolor/16x16/apps/zeal.png" },
 }

 local menu52dd1c847264a75f400961bfb4d1c849 = {
     {"Audio Mixer", "xfce4-mixer"},
     {"Clementine", "clementine ", "/usr/share/icons/hicolor/64x64/apps/application-x-clementine.png" },
     {"Dragon Player", "dragon ", "/usr/share/icons/hicolor/16x16/apps/dragonplayer.png" },
     {"JuK", "juk -caption JuK ", "/usr/share/icons/hicolor/16x16/apps/juk.png" },
     {"KsCD", "kscd -caption KsCD ", "/usr/share/icons/hicolor/16x16/apps/kscd.png" },
     {"Qt V4L2 test Utility", "qv4l2", "/usr/share/icons/hicolor/16x16/apps/qv4l2.png" },
     {"SMPlayer", "smplayer ", "/usr/share/icons/hicolor/16x16/apps/smplayer.png" },
     {"Spotify", "spotify ", "/usr/share/icons/hicolor/16x16/apps/spotify-client.png" },
     {"Tomahawk", "tomahawk ", "/usr/share/icons/hicolor/16x16/apps/tomahawk.png" },
     {"VLC media player", "/usr/bin/vlc --started-from-file ", "/usr/share/icons/hicolor/16x16/apps/vlc.png" },
 }

 local menuee69799670a33f75d45c57d1d1cd0ab3 = {
     {"Avahi Zeroconf Browser", "/usr/bin/avahi-discover"},
     {"Dolphin", "dolphin  -caption Dolphin "},
     {"File Manager PCManFM", "pcmanfm "},
     {"Htop", "xterm -e htop", "/usr/share/pixmaps/htop.png" },
     {"KDiskFree", "kdf -caption KDiskFree", "/usr/share/icons/hicolor/16x16/apps/kdf.png" },
     {"KSysGuard", "ksysguard "},
     {"KSystemLog", "xdg_menu_su ksystemlog  -caption KSystemLog"},
     {"KUser", "xdg_menu_su kuser  -caption KUser", "/usr/share/icons/hicolor/16x16/apps/kuser.png" },
     {"KWalletManager", "kwalletmanager ", "/usr/share/icons/hicolor/16x16/apps/kwalletmanager.png" },
     {"Konsole", "konsole"},
     {"Krfb", "krfb -caption Krfb "},
     {"KwikDisk", "kwikdisk -caption KwikDisk", "/usr/share/icons/hicolor/16x16/apps/kwikdisk.png" },
     {"Terminator", "terminator", "/usr/share/icons/hicolor/16x16/apps/terminator.png" },
     {"dconf Editor", "dconf-editor", "/usr/share/icons/hicolor/16x16/apps/dconf-editor.png" },
 }

xdgmenu = {
    {"Accessibility", menue0e4fc6213e8b3593495a7260c3a4c2e},
    {"Accessories", menu98edb85b00d9527ad5acebe451b3fae6},
    {"Education", menude7a22a0c94aa64ba2449e520aa20c99},
    {"Games", menu251bd8143891238ecedc306508e29017},
    {"Graphics", menud334dfcea59127bedfcdbe0a3ee7f494},
    {"Internet", menuc8205c7636e728d448c2774e6a4a944b},
    {"Office", menudf814135652a5a308fea15bff37ea284},
    {"Programming", menue6f43c40ab1c07cd29e4e83e4ef6bf85},
    {"Sound & Video", menu52dd1c847264a75f400961bfb4d1c849},
    {"System Tools", menuee69799670a33f75d45c57d1d1cd0ab3},
}

