#!/usr/bin/env bash
# Grabs and prints information about the weather (in Cincinnati) from accuweather.com

URL='http://www.accuweather.com/en/us/cincinnati-oh/45212/weather-forecast/350126'

weather="$(curl -s "$URL" | awk -F\' '/acm_RecentLocationsCarousel\.push/{print $14", "$12"°" }'| head -1)"

if [[ $weather == *thunder* || $weather == *Thunder* ]]; then
    echo ' '$weather
else
    if [[ $weather == *rain* || $weather == *Rain* ]]; then
        echo ' '$weather
    else
        if [[ $weather == *cloud* || $weather == *Cloud* ]]; then
            echo ' '$weather
        else
            echo ' '$weather
        fi
    fi
fi