* Emacs Org Configuration
2014-10-25
* Description
This file is tangled using =org-babel-load-file=. What this does is generate
a =emacs-init.el= from the =emacs-lisp= source blocks.

This emacs.d is currently  designed for Emacs 24.3 and above.

**** The basic directory structure.
#+BEGIN_SRC text
  └── emacs.d
      ├── README.markdown
      ├── emacs-init.org
      ├── init.el
      ├── packages
      ├── places
      ├── snippets
      ├── backups
      ├── tempfiles
      └── themes
#+END_SRC

*** Credits:
This emacs.d was heavily inspired by the following configurations.

[[https://github.com/magnars/.emacs.d][Magnar Sveen's emacs.d]]

[[https://github.com/jhenahan/emacs.d/blob/master/emacs-init.org][Jack Henahan's init.org]]

[[https://github.com/seth/my-emacs-dot-d/blob/master/emacs-init.org][Seth Falcon's emacs-init-org]]

[[https://github.com/steckerhalter/steckemacs/blob/master/steckemacs.org][Steckerhalter's Steckemacs]]

[[https://github.com/daschwa/dotfiles][Daschwa's Dotfiles]]

* Prerequisites

** Arch Linux

*** [[https://wiki.archlinux.org/index.php/Pacaur][Pacaur (or any other AUR helepr)]]

*** [[https://github.com/cask/cask][Cask]]
#+BEGIN_SRC sh
pacaur -S cask
#+END_SRC

* Installation

** Arch Linux
*** Installing Emacs
**** 24.4 (Stable)
#+BEGIN_SRC sh
pacman -S emacs
#+END_SRC

* Package Management

[[https://github.com/rdallasgray/pallet][Pallet]] is a very helpful package management tool for Emacs.
It utilizes a dependency management platform called [[https://github.com/cask/cask][Cask]],
to update a centralized =Cask= file when you install or remove packages.

** Pallet
You can download all packages in your =Cask= file by using =M-x pallet-install=.
However, this should not be necessary.

** Cask
Cask is initialized in =init.el= with the following:
#+BEGIN_SRC emacs-lisp
(require 'cask "/usr/share/cask/cask.el")
(cask-initialize)
#+END_SRC

** Install Packages
- Install [[https://github.com/cask/cask][Cask]].
- Run =cask install= in =$HOME/.emacs.d/=.

* Packages, Modes, and Extensions
** Dependency Management with =req-package=

Where Pallet keeps track of the packages we have installed, =req-package=
handles all our internal package dependencies and configurations.

#+BEGIN_QUOTE
[[https://github.com/edvorg/req-package][req-package]] is a wrapper on top of [[https://github.com/jwiegley/use-package][use-package]], a package dependency
management tool. The documentation for =use-package= is immensely helpful for
figuring out how to describe package dependencies and settings. =req-package=
adds the =:require= keyword which allows you to define dependencies between
related packages.
#+END_QUOTE

Another nice thing about =req-package=, is that you no longer not need to
specify the =:ensure= keyword, as it is added by default.

Start using =req-package=
#+BEGIN_SRC emacs-lisp
(require 'req-package)
#+END_SRC

** Local Custom Packages
Add custom packages directory to the =load-path=.
#+BEGIN_SRC emacs-lisp
  (add-to-list 'load-path (concat user-emacs-directory "packages/"))
#+END_SRC

* Essentials
Some quick essential customizations. To tame emacs's
#+BEGIN_SRC emacs-lisp
  ;; Turn off mouse interface early in startup to avoid momentary display
  (if (fboundp 'menu-bar-mode) (menu-bar-mode -1))
  (if (fboundp 'tool-bar-mode) (tool-bar-mode -1))
  (if (fboundp 'scroll-bar-mode) (scroll-bar-mode -1))

  ;; Start off with some sanity.
  (req-package better-defaults)

  ;; No splash screen please
  (setq inhibit-startup-message t)

  ;; No alarms.
  (setq ring-bell-function 'ignore)

  ;; Write backup files to own directory
  (setq backup-directory-alist
        `(("." . ,(expand-file-name
                   (concat user-emacs-directory "backups")))))

  ;; Backup files correctly and clean up versions
  (setq backup-by-copying t)
  (setq delete-old-versions t)
  (setq kept-new-versions 6)
  (setq kept-old-versions 2)
  (setq version-control t)

  ;; Disable lock files
  (setq create-lockfiles nil)

  ;; Write auto-saves to own directory
  (setq auto-save-file-name-transforms
        `((".*" ,(expand-file-name
                  (concat user-emacs-directory "tempfiles")) t)))


  ;; Make backups of files, even when they're in version control
  (setq vc-make-backup-files t)

  ;; Save point position between sessions
  (req-package saveplace)
  (setq-default save-place t)
  (setq save-place-file (expand-file-name "places" user-emacs-directory))

  ;; Fix empty pasteboard error
  (setq save-interprogram-paste-before-kill nil)

  ;; Enable some commands
  (put 'downcase-region 'disabled nil)
  (put 'upcase-region 'disabled nil)
  (put 'narrow-to-region 'disabled nil)
  (put 'erase-buffer 'disabled nil)

  ;; Allow pasting selection outside Emacs
  (setq x-select-enable-clipboard t)

  ;; Move deleted fiels to trash
  (setq delete-by-moving-to-trash t)

  ;; No shift marking/selecting
  (setq shift-select-mode nil)

  ;; Answer yes/no with y/n
  (defalias 'yes-or-no-p 'y-or-n-p)

  ;; Set coding system to utf-8 everywhere
  (setq locale-coding-system 'utf-8)
  (set-terminal-coding-system 'utf-8)
  (set-keyboard-coding-system 'utf-8)
  (set-selection-coding-system 'utf-8)
  (prefer-coding-system 'utf-8)

  ;; Use spaces by defult
  (setq-default indent-tabs-mode nil)
  (setq-default tab-width 2)

  ;; Line and column numbers
  (setq line-number-mode t)
  (setq column-number-mode t)
#+END_SRC

* Keybindings
#+BEGIN_QUOTE
There are a number of ways to bind keys in Emacs, but I find
=bind-key=, bundled with =use-package=, easier to work with and,
more importantly, easier to read. =bind-key= takes a key sequence, a
command, and an optional keymap.  =bind-key*= overrides any minor
mode which sets the keybinding. =unbind-key= takes a key sequence
and a keymap and removes that binding. Invoking
=describe-personal-keybindings= prints a summary of your keybindings
through =bind-key= and any overrides or conflicts. This is really
the killer convenience of using =bind-key=.
#+END_QUOTE

** Exiting
I don't like to quit Emacs on accident, and I find closing frames are more useful.

#+BEGIN_SRC emacs-lisp
  ;; The mnemonic is C-x REALLY QUIT
  (bind-key "C-x r q" 'save-buffers-kill-terminal)
  (bind-key "C-x C-c" 'delete-frame)
#+END_SRC

** Improvements
#+BEGIN_SRC emacs-lisp
  ;; Home and End Keys:
  (bind-key "<home>" 'move-beginning-of-line)
  (bind-key "<end>" 'move-end-of-line)

  ;; Joins Lines into one
  (bind-key  "M-j" '(lambda () (interactive) (join-line -1)))

  ;; Kill line from the left
  (bind-key "<s-backspace>" '(lambda () (interactive) (kill-line 0)))

  ;; Quickly jump to last change
  (bind-key "C-x C-\\" 'goto-last-change)

  ;; Clean up whitespace
  (bind-key "C-c @ c" 'delete-trailing-whitespace)

  ;; Replace string
  (bind-key "C-c r" 'replace-string)
#+END_SRC

** Unbind keys
Sometimes there are system keybindings that get in the way and will be used later.

#+BEGIN_SRC emacs-lisp
(dolist (keys '("<M-up>" "<M-down>" "<s-left>" "<s-right>"
                "s-c" "s-v" "s-x" "s-v" "s-q" "s-s" "s-w"
                "s-a" "s-o" "s-n" "s-p" "s-k" "s-u" "s-m"
                "s-f" "s-z" "s-g" "s-d" "s-," "s-:" "s-e"
                "s-t" "C-z"))
  (global-unset-key (kbd keys)))
#+END_SRC

* TODO Appearance
** Font
I default to DejaVu Sans Mono for everything.
#+BEGIN_SRC emacs-lisp
   (set-face-attribute 'default nil :family "DejaVu Sans Mono" :height 98)
#+END_SRC

** Theme
Set custom theme path and load theme
#+BEGIN_SRC emacs-lisp
(setq custom-theme-directory (concat user-emacs-directory "themes/"))

(load-theme 'smyx-custom t)
#+END_SRC

** Pretty Mode
#+BEGIN_SRC emacs-lisp
  (req-package pretty-mode
    :config
    (global-pretty-mode 1))
#+END_SRC

** TODO Mode Line
*** Date
Display the date on the mode line.
#+BEGIN_SRC emacs-lisp
(setq display-time-day-and-date t
                display-time-format "%a %b %d %R"
                display-time-interval 60
                display-time-default-load-average nil)
             (display-time)
#+END_SRC

*** TODO Use a custom powerline theme that includes workgroup and evil support
#+BEGIN_SRC emacs-lisp
  (req-package powerline
               :config
               (powerline-default-theme))
#+END_SRC

** Custom Keywords

*** Keyword Symbols
#+BEGIN_SRC emacs-lisp
(defun add-operator-hl ()
  (font-lock-add-keywords
   nil
   '(("\s[-]\s\\|\s[/]\s\\|[%]\\|[+]\\|[*]\\|[!=]\\|[/=]\\|[<=]\\|[>=]" . font-lock-keyword-face))))
;; prog-mode applies to all programming modes
(add-hook 'prog-mode-hook 'add-operator-hl)
#+END_SRC

** Other
Don't defer screen updates when performing operations
#+BEGIN_SRC emacs-lisp
(setq redisplay-dont-pause t)
#+END_SRC

* Setups
  All packages and modes are configured here.
** Minor Modes and Utilities
*** Pallet
#+BEGIN_SRC emacs-lisp
(req-package pallet)
#+END_SRC

*** IDO
#+BEGIN_SRC emacs-lisp
  (req-package ido
               :require (flx-ido ido-vertical-mode ido-ubiquitous)
               :init
               (progn
                 (ido-mode t)

                 (flx-ido-mode 1)
                 (setq ido-use-faces nil)

                 (ido-vertical-mode)

                 ;; Use ido everywhere
                 (ido-ubiquitous-mode 1)))
#+END_SRC

*** Smex
[[https://github.com/nonsequitur/smex][Smex]] brings ido searching to =M-x=.

#+BEGIN_SRC emacs-lisp
  (req-package smex
               :require ido
               :bind (("M-x" . smex)
                      ("M-X" . smex-major-mode-commands)))
#+END_SRC

*** Diminish
Move to setups for diminish and use =req-package=
Removes minor modes from the mode line.
Can get back with =M-x RET diminish-undo=
=diminish= is integrated with =req-package=.
#+BEGIN_SRC emacs-lisp
(req-package diminish)
#+END_SRC

*** Company
[[http://company-mode.github.io/][Company]] is a text completion framework for Emacs. It stands for "complete anything".
#+BEGIN_SRC emacs-lisp
  (req-package company
    :diminish (company-mode . "")
    :config
    (progn
      (setq company-idle-delay 0.3)
      (setq company-tooltip-limit 20)
      (setq company-minimum-prefix-length 2)
      (global-company-mode t)))
#+END_SRC

*** Ace-Jump-Mode
Quickly navigate inside a buffer.

=C-u C-c s= lets you search for any character despite its position in a word.

=C-u <C-space>= pops the mark and brings your point back to where it was earlier.

#+BEGIN_SRC emacs-lisp
(req-package ace-jump-mode
             :bind ("C-c SPC" . ace-jump-mode))
#+END_SRC

*** Recent Files
#+BEGIN_SRC emacs-lisp
  (req-package recentf
               :config
               (progn
                 (recentf-mode 1)
                 (setq recentf-max-saved-items 100)
                 (setq recentf-max-menu-items 15)))

  ;; Looks like a big mess
  (defun recentf-ido-find-file ()
    "Find a recent file using ido."
    (interactive)
    (let ((file (ido-completing-read "Choose recent file: " recentf-list nil t)))
      (when file
        (find-file file))))
  (bind-key "C-x C-r" 'recentf-ido-find-file)
#+END_SRC

*** Yasnippet
Snippets are key.
#+BEGIN_SRC emacs-lisp
  (req-package yasnippet
               :diminish (yas-global-mode . "")
               :init
               (progn
                 (setq yas-snippet-dirs '("~/.emacs.d/snippets/"))
                 (add-to-list 'auto-mode-alist '("yasnippet/snippets" . snippet-mode))
                 (add-to-list 'auto-mode-alist '("\\.yasnippet$" . snippet-mode)))
               :config
               (progn
                 (yas-global-mode 1)
                 ;; No dropdowns please, yas
                 (setq yas-prompt-functions '(yas/ido-prompt yas/completing-prompt))
                 ;; No need to be so verbose
                 (setq yas-verbosity 1)
                 ;; Wrap around region
                 (setq yas-wrap-around-region t)
                 ;; Bind only during snippet
                 (bind-key "<return>" 'yas/exit-all-snippets yas-keymap)
                 (bind-key "C-e" 'yas/goto-end-of-active-field yas-keymap)
                 (bind-key "C-a" 'yas/goto-start-of-active-field yas-keymap)))

  ;; Interactive-Field navigation
  (defun yas/goto-end-of-active-field ()
    (interactive)
    (let* ((snippet (car (yas--snippets-at-point)))
           (position (yas--field-end (yas--snippet-active-field snippet))))
      (if (= (point) position)
          (move-end-of-line 1)
        (goto-char position))))

  (defun yas/goto-start-of-active-field ()
    (interactive)
    (let* ((snippet (car (yas--snippets-at-point)))
           (position (yas--field-start (yas--snippet-active-field snippet))))
      (if (= (point) position)
          (move-beginning-of-line 1)
        (goto-char position))))

  ;; fix some org-mode + yasnippet conflicts:
  (defun yas/org-very-safe-expand ()
    (let ((yas/fallback-behavior 'return-nil)) (yas/expand)))
#+END_SRC

yasnippet is "disabled" in =emacs-lisp-mode=
by appending a =-= in front of the =emacs-lisp= directory in =snippets/=.

*** Undo-Tree
More natural undo or redo. Undo with =C-/= and redo with =C-?=.

#+BEGIN_SRC emacs-lisp
  (req-package undo-tree
    :diminish (undo-tree-mode . "")
    :bind (("C-x x u" . undo-tree-visualize)
           ("C-x x r u" . undo-tree-save-state-to-register)
           ("C-x x r U" . undo-tree-restore-state-from-register))
    :config
    (progn
      (global-undo-tree-mode 1)
      ;; Fix some undo-tree bindings.
      (unbind-key "C-x u" undo-tree-map)
      (unbind-key "C-x r u" undo-tree-map)
      (unbind-key "C-x r U" undo-tree-map)))
#+END_SRC

*** Move-Text
Move lines or a region up or down.

#+BEGIN_SRC emacs-lisp
(req-package move-text
             :bind (("<C-S-up>" . move-text-up)
                    ("<C-S-down>" . move-text-down)))
#+END_SRC

*** Web Jump
#+BEGIN_SRC emacs-lisp
(req-package webjump
             :bind ("C-c j" . webjump))
#+END_SRC

This adds Urban Dictionary to webjup. It serves as an example to add more sites later.

#+BEGIN_SRC emacs-lisp
(req-package webjump
             :init
             (add-to-list 'webjump-sites
                          '("Urban Dictionary" .
                            [simple-query
                             "www.urbandictionary.com"
                             "http://www.urbandictionary.com/define.php?term="
                             ""])))
#+END_SRC

*** Go-To URL
#+BEGIN_SRC emacs-lisp
(req-package browse-url
             :bind ("C-c C-j" . browse-url))
#+END_SRC

*** Smartparens
Show matching and unmatched delimiters, and auto-close them as well.

#+BEGIN_SRC emacs-lisp
  (req-package smartparens
               :diminish (smartparens-mode . "")
               :config
               (progn
                 (smartparens-global-mode t)
                 ;; The '' pair will autopair UNLESS the point is right after a word,
                 ;; in which case you want to insert a single apostrophe.
                 (sp-pair "'" nil :unless '(sp-point-after-word-p))

                 ;; disable single quote completion in
                 ;; emacs-lisp-mode WHEN point is inside a string. In other modes, the
                 ;; global definition is used.
                 (sp-local-pair 'emacs-lisp-mode "'" nil :when '(sp-in-string-p))
                 (sp-local-pair 'lisp-interaction-mode "'" nil :when '(sp-in-string-p))))
#+END_SRC

*** Smart Compile
Set custom compile commands for different modes.

#+BEGIN_SRC emacs-lisp
  (req-package smart-compile
    :bind ("C-x c c" . smart-compile)
    :config
    (progn
      (remove '("\\.c\\'" . "gcc -O2 %f -lm -o %n") 'smart-compile-alist)
      ;; compile and run programs
      (add-to-list 'smart-compile-alist '("\\.c\\'" . "gcc -O2 -Wall %f -lm -o %n"))
      (add-to-list 'smart-compile-alist '("\\.cpp\\'" . "g++ -Wall -ggdb %f -lm -o %n"))
      (add-to-list 'smart-compile-alist '("\\.py\\'" . "python %f"))
      (add-to-list 'smart-compile-alist '("\\.hs\\'" . "ghc -o %n %f"))
      (add-to-list 'smart-compile-alist '("\\.js\\'" . "node %f"))))
#+END_SRC

*** Make File
Use tabs only in a makefile.

#+BEGIN_SRC emacs-lisp
(defun my-tabs-makefile-hook ()
  (setq indent-tabs-mode t))
(add-hook 'makefile-mode-hook 'my-tabs-makefile-hook)
#+END_SRC

*** Rainbow Mode
=rainbow-mode= displays hexadecimal colors with the color they represent as their background.
#+BEGIN_SRC emacs-lisp
(req-package rainbow-mode
             :diminish (rainbow-mode . "")
             :init
             (add-hook 'prog-mode-hook 'rainbow-mode))
#+END_SRC

*** Flyspell
Enable spell-checking in Emacs.
**** Aspell
#+BEGIN_SRC sh
pacman -S aspell
#+END_SRC

**** Emacs:
#+BEGIN_SRC emacs-lisp
  (req-package flyspell
               :diminish (flyspell-mode . "")
               :init
               (progn
                 ;; Enable spell check in program comments
                 (add-hook 'prog-mode-hook 'flyspell-prog-mode)
                 ;; Enable spell check in plain text / org-mode
                 (add-hook 'text-mode-hook 'flyspell-mode)
                 (add-hook 'org-mode-hook 'flyspell-mode)
                 :config
                 (setq flyspell-issue-welcome-flag nil)
                 (setq flyspell-issue-message-flag nil)

                 ;; ignore repeated words
                 (setq flyspell-mark-duplications-flag nil)

                 (setq-default ispell-list-command "list")

                 ;; Make spell check on right click.
                 (define-key flyspell-mouse-map [down-mouse-3] 'flyspell-correct-word)
                 (define-key flyspell-mouse-map [mouse-3] 'undefined)))

#+END_SRC
**** Helpful Default Keybindings
=C-.= corrects word at point.
=C-,​= to jump to next misspelled word.

*** Flycheck
A great syntax checker.
#+BEGIN_SRC emacs-lisp
  (req-package flycheck
               :diminish (flycheck-mode . "")
               :config
               (progn
                 (add-hook 'after-init-hook #'global-flycheck-mode)
                 (setq-default flycheck-disabled-checkers '(emacs-lisp-checkdoc)) ; disable the annoying doc checker
                 (setq flycheck-indication-mode 'left-fringe)
                 (defun magnars/adjust-flycheck-automatic-syntax-eagerness ()
                   "Adjust how often we check for errors based on if there are any.

  This lets us fix any errors as quickly as possible, but in a
  clean buffer we're an order of magnitude laxer about checking."
                   (setq flycheck-idle-change-delay
                         (if flycheck-current-errors 0.5 30.0)))

                 ;; Each buffer gets its own idle-change-delay because of the
                 ;; buffer-sensitive adjustment above.
                 (make-variable-buffer-local 'flycheck-idle-change-delay)

                 (add-hook 'flycheck-after-syntax-check-hook
                           'magnars/adjust-flycheck-automatic-syntax-eagerness)

                 ;; Remove newline checks, since they would trigger an immediate check
                 ;; when we want the idle-change-delay to be in effect while editing.
                 (setq flycheck-check-syntax-automatically '(save
                                                             idle-change
                                                             mode-enabled))

                 (defun flycheck-handle-idle-change ()
                   "Handle an expired idle time since the last change.

  This is an overwritten version of the original
  flycheck-handle-idle-change, which removes the forced deferred.
  Timers should only trigger inbetween commands in a single
  threaded system and the forced deferred makes errors never show
  up before you execute another command."
                   (flycheck-clear-idle-change-timer)
                   (flycheck-buffer-automatically 'idle-change))))
#+END_SRC

*** Helm
=helm-mini= is a part of [[https://github.com/emacs-helm/helm][Helm]] that shows current buffers and a list of recent files using =recentf=.
It is a great way to manage many open files.

#+BEGIN_SRC emacs-lisp
  (req-package helm-config
               :require (helm-misc popwin flycheck helm-dash helm-spotify helm-dash)
               :bind (("C-c h" . helm-mini)
                      ("C-c C-h m" . helm-spotify)
                      ("C-c C-h d" . helm-dash)
                      ("C-c C-h C-d" . helm-dash-at-point)
                      ("C-c ! h" . helm-flycheck))
               :init
               (progn
                 (setq popwin:special-display-config
                       (push helm-popwin
                             popwin:special-display-config))
                 (setq helm-dash-browser-func 'eww)
                 ))
#+END_SRC

*** Pop Win
[[https://github.com/m2ym/popwin-el][popwin]] is used to manage the size of "popup" buffers.

#+BEGIN_SRC emacs-lisp
(req-package popwin
             :config
             (progn
               (popwin-mode 1)
               (setq helm-popwin
                     '("*helm mini*" :height 10))))
#+END_SRC

*** Multiple Cursors
[[https://github.com/emacsmirror/multiple-cursors][Multiple Cursors]] brings you seemingly unlimited power.

#+BEGIN_SRC emacs-lisp
    ;; Create new cursor by marking region with up / down arrows.
    (req-package rectangular-region-mode
                 :require multiple-cursors-core
                 :bind ("C-c C-SPC" . set-rectangular-region-anchor))
    ;; Mark by keyword
    (req-package mc-mark-more
                 :require (multiple-cursors-core thingatpt)
                 :bind (("C-c C->" . mc/mark-next-like-this)
                        ("C-c C-<" . mc/mark-previous-like-this)
                        ( "C-c c s" . mc/mark-all-like-this)
                        ("M-<mouse-1>" . mc/add-cursor-on-click)))
#+END_SRC

*** Expand Region
Make selections based on semantic units / delimiters like quotes, parens, or markup tags.
#+BEGIN_SRC emacs-lisp
(req-package expand-region
             :require (expand-region-core expand-region-custom er-basic-expansions)
             :bind ("C-=" . er/expand-region))
#+END_SRC

*** Winner Mode
#+BEGIN_SRC emacs-lisp
  ;; Turn on winner mdoe by defautl
  (winner-mode 1)
#+END_SRC

*** Auto Compression Mode
#+BEGIN_SRC emacs-lisp
  ;; Transparently open compressed files
  (auto-compression-mode t)
#+END_SRC

*** Linum Mode
#+BEGIN_SRC emacs-lisp
  ;; Global line numbers
  (global-linum-mode 1)
#+END_SRC

*** Flex isearch
#+BEGIN_SRC emacs-lisp
  ;; Flex isearch
  (req-package flex-isearch
               :init
               (global-flex-isearch-mode 1))
#+END_SRC

*** Delete Select
#+BEGIN_SRC emacs-lisp
  ;; Remove test in active region if inserting text
  (req-package delsel
               :init
               (delete-selection-mode 1))

#+END_SRC

*** Uniquify
#+BEGIN_SRC emacs-lisp
  ;; Add parts of each file's directory to the buffer name if not unique
  (req-package uniquify
               :init
               (setq uniquify-buffer-name-style 'forward))

#+END_SRC

*** Projectile
#+BEGIN_SRC emacs-lisp
  ;; Projectile
  (req-package projectile
               :init
               (projectile-global-mode))

#+END_SRC

*** Show Parens
#+BEGIN_SRC emacs-lisp
;; Show matchin parentheses
(show-paren-mode 1)
#+END_SRC

*** Same-Frame Speedbar
#+BEGIN_SRC emacs-lisp
  ;; Same-frame Speedbar
  (req-package sr-speedbar
               :bind ("C-c C-s" . sr-speedbar-toggle)
               :config
               (progn
                 (setq speedbar-show-unknown-files t)
                 (setq speedbar-smart-directory-expand-flag t)
                 (setq speedbar-use-images nil)))

#+END_SRC

*** EWW
#+BEGIN_SRC emacs-lisp
(require 'eww)
(setq browse-url-browser-function 'eww)
#+END_SRC

*** Tramp
#+BEGIN_SRC emacs-lisp
;; Make tramp work nicely with sudo
(set-default 'tramp-default-proxies-alist (quote ((".*" "\\`root\\'" "/ssh:%h:"))))
#+END_SRC

*** Guide Key
#+BEGIN_SRC emacs-lisp
  (req-package guide-key
               :diminish (guide-key-mode . "")
               :init
               (progn
                 (setq guide-key/guide-key-sequence '("C-x" "C-c"))
                 (setq guide-key/recursive-key-sequence-flag t)
                 (guide-key-mode 1)))
#+END_SRC

*** Pass
#+BEGIN_SRC emacs-lisp
  (req-package password-store)
#+END_SRC

*** Comment DWIM 2
#+BEGIN_SRC emacs-lisp
    (req-package comment-dwim-2
                 :bind ("M-;" . comment-dwim-2))
#+END_SRC

*** Math At Point
#+BEGIN_SRC emacs-lisp
    (req-package math-at-point)
#+END_SRC

*** Workgroups
#+BEGIN_SRC emacs-lisp
  (req-package workgroups-mode
               :config
               (progn
                 (setq wg-prefix-key (kbd "C-z"))
                 (setq wg-session-file "~/.emacs.d/.emacs_workgroups")
                 (workgroups-mode 1)))
#+END_SRC

*** Smart Forward
#+BEGIN_SRC emacs-lisp
  (req-package smart-forward
               :bind (("M-<up>" . smart-up)
                      ("M-<down>" . smart-down)
                      ("M-<left>" . smart-left)
                      ("M-<right>" . smart-right)))
#+END_SRC

*** Diff Hightlight
#+BEGIN_SRC emacs-lisp
  (req-package diff-hl
               :init
               (global-diff-hl-mode))
#+END_SRC

*** Dedicated
#+BEGIN_SRC emacs-lisp
    (req-package dedicated)
#+END_SRC

*** Evil
#+BEGIN_SRC emacs-lisp
  (req-package evil
               :require (ace-jump-mode)
               :bind ("C-c [ESC]" . evil-mode)
               :init
               (progn
                 (setq evil-default-cursor t)))
#+END_SRC

** Major Modes
*** Lisp
#+BEGIN_SRC emacs-lisp
  (req-package lisp-mode
               :init
               (progn
                 (add-hook 'emacs-lisp-mode-hook 'turn-on-eldoc-mode)
                 (add-hook 'lisp-interaction-mode-hook 'turn-on-eldoc-mode)))
#+END_SRC

*** Python
**** Elpy Mode
[[https://github.com/jorgenschaefer/elpy][Elpy]] combines many helpful packages for working with Python.

#+BEGIN_SRC sh
  pip install elpy
  pip install jedi
  pip install rope # optional
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (req-package elpy
    :config
    (progn
      (elpy-enable)
      ;; Use Flycheck instead of Flymake
      (when (require 'flycheck nil t)
        (remove-hook 'elpy-modules 'elpy-module-flymake)
        (add-hook 'elpy-mode-hook 'flycheck-mode))
      ;; jedi is great
      (setq elpy-rpc-backend "jedi")))

#+END_SRC

*** Web Mode
[[http://web-mode.org/][web-mode]] is by far the best major mode I have found for editing HTML.
**** HTML
#+BEGIN_SRC emacs-lisp
  (req-package web-mode
               :bind ("C-c C-v" . browse-url-of-buffer)
               :init
               (progn
                 (add-to-list 'auto-mode-alist '("\\.html?\\'" . web-mode))
                 (add-to-list 'auto-mode-alist '("\\.jsp$" . web-mode))
                 (add-to-list 'auto-mode-alist '("\\.php\\'" . web-mode))
                 (add-to-list 'auto-mode-alist '("\\.tpl\\.php\\'" . web-mode)))
               :config
               (progn
                 ;; Set tab to 4 to play nice with plebeian editors
                 (setq web-mode-markup-indent-offset 2)
                 (setq web-mode-css-indent-offset 4)
                 (setq web-mode-code-indent-offset 4)
                 (bind-key "<return>" 'newline-and-indent web-mode-map)
                 (bind-key "C-c w t" 'web-mode-element-wrap)))
#+END_SRC

***** Helpful Default Bindings
=C-c C-f= folds html tags.

=C-c C-n= moves between the start / end tag.

=C-c C-w= shews problematic white-space.

**** CSS
#+BEGIN_SRC emacs-lisp
  (req-package css-mode
               :init
               (progn
                 (add-to-list 'auto-mode-alist '("\\.scss$" . css-mode))
                 (add-to-list 'auto-mode-alist '("\\.sass$" . css-mode))
                 (add-to-list 'auto-mode-alist '("\\.less" . css-mode)))
               :config
               (progn
                 (add-hook 'css-mode-hook 'turn-on-css-eldoc)
                 (add-hook 'css-mode-hook 'rainbow-mode)
                 (autoload 'turn-on-css-eldoc "css-eldoc")
                 (bind-key "C-{" 'brace-ret-brace css-mode-map)))

  ;; Insert curly-braces
  (defun brace-ret-brace ()
    (interactive)
    (insert "{") (newline-and-indent)
    (newline-and-indent)
    (insert "}") (indent-for-tab-command)
    (newline-and-indent) (newline-and-indent)
    (previous-line) (previous-line) (previous-line)
    (indent-for-tab-command))
#+END_SRC

**** Emmet
[[http://emmet.io/][Emmet]] is supper cool, and [[https://github.com/smihica/emmet-mode][emmet-mode]] brings support to Emacs.

#+BEGIN_SRC emacs-lisp
(req-package emmet-mode
             :init
             (progn
               (add-hook 'sgml-mode-hook 'emmet-mode)
               (add-hook 'web-mode-hook 'emmet-mode)
               (add-hook 'css-mode-hook  'emmet-mode))
             :config
             (progn
               (setq emmet-indentation 2)
               (bind-key "C-j" 'emmet-expand-line emmet-mode-keymap)
               (bind-key "<C-return>" 'emmet-expand emmet-mode-keymap)
               ;; Remove purple <, >.
               (defadvice emmet-preview-accept (after expand-and-fontify activate)
                 "Update the font-face after an emmet expantion."
                 (font-lock-fontify-buffer))))
#+END_SRC

**** Web Defuns
#+BEGIN_SRC emacs-lisp
  (defun skip-to-next-blank-line ()
    (interactive)
    (let ((inhibit-changing-match-data t))
      (skip-syntax-forward " >")
      (unless (search-forward-regexp "^\\s *$" nil t)
        (goto-char (point-max)))))

  (defun skip-to-previous-blank-line ()
    (interactive)
    (let ((inhibit-changing-match-data t))
      (skip-syntax-backward " >")
      (unless (search-backward-regexp "^\\s *$" nil t)
        (goto-char (point-min)))))

  (defun html-wrap-in-tag (beg end)
    (interactive "r")
    (let ((oneline? (= (line-number-at-pos beg) (line-number-at-pos end))))
      (deactivate-mark)
      (goto-char end)
      (unless oneline? (newline-and-indent))
      (insert "</div>")
      (goto-char beg)
      (insert "<div>")
      (unless oneline? (newline-and-indent))
      (indent-region beg (+ end 11))
      (goto-char (+ beg 4))))

  (eval-after-load "sgml-mode"
    '(progn
       ;; don't include equal sign in symbols
       (modify-syntax-entry ?= "." html-mode-syntax-table)

       (define-key html-mode-map [remap forward-paragraph] 'skip-to-next-blank-line)
       (define-key html-mode-map [remap backward-paragraph] 'skip-to-previous-blank-line)
       ;;(define-key html-mode-map (kbd "C-c C-w") 'html-wrap-in-tag)
       (define-key html-mode-map (kbd "/") nil) ; no buggy matching of slashes
       (define-key html-mode-map (kbd "C-c C-d") 'ng-snip-show-docs-at-point)))

  ;; after deleting a tag, indent properly
  (defadvice sgml-delete-tag (after reindent activate)
    (indent-region (point-min) (point-max)))
#+END_SRC

*** Geiser / Scheme
**** Dr. Racket:
#+BEGIN_SRC sh
pacman -S racket
#+END_SRC

**** Geiser:
#+BEGIN_SRC sh
pacman -S guile
#+END_SRC

**** Emacs:
#+BEGIN_SRC emacs-lisp
  (req-package scheme
               :init
               (progn
                 (setq geiser-racket-binary "/usr/bin/racket")
                 (setq geiser-guile-binary "/usr/bin/guile")))
#+END_SRC

*** LaTeX
**** Setup
Install ImageMagick, Pygments, and extra LaTeX packages.
#+BEGIN_SRC sh
pacman -S imagemagick texlive-most texlive-lang
pip install Pygments
#+END_SRC

**** AUCTeX
#+BEGIN_SRC emacs-lisp
(req-package tex-site
             :init
             (progn
               (setq TeX-PDF-mode t)
               (setq LaTeX-command "latex -shell-escape")))
#+END_SRC

*** Org Mode
If you are not using it, you need to start.
#+BEGIN_SRC emacs-lisp
    (req-package org
    :require (ob-core ox-md ox-latex)
    :config
    (progn
      ;; Unbind from org-mode only
      (unbind-key "<C-S-up>" org-mode-map)
      (unbind-key "<C-S-down>" org-mode-map)
      ;; Bind new keys to org-mode only
      (bind-key "<s-up>" 'org-metaup org-mode-map)
      (bind-key "<s-down>" 'org-metadown org-mode-map)
      (bind-key "<s-left>" 'org-promote-subtree org-mode-map)
      (bind-key "<s-right>" 'org-demote-subtree org-mode-map)

      ;; Fontify org-mode code blocks
      (setq org-src-fontify-natively t)

      ;; Essential Settings
      (setq org-log-done 'time)
      (setq org-html-doctype "html5")
      (setq org-export-headline-levels 6)

      ;; Custom TODO keywords
      (setq org-todo-keywords
            '((sequence "TODO(t)" "WAIT(w@/!)" "|" "DONE(d!)" "CANCELED(c@)")))

      ;; Set up latex
      (setq org-export-with-LaTeX-fragments t)
      (setq org-latex-create-formula-image-program 'imagemagick)

      ;; Add minted to the defaults packages to include when exporting.
      (add-to-list 'org-latex-packages-alist '("" "minted"))

      ;; Tell the latex export to use the minted package for source
      ;; code coloration.
      (setq org-latex-listings 'minted)

      ;; Let the exporter use the -shell-escape option to let latex
      ;; execute external programs.
      (setq org-latex-pdf-process
            '("pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"))

      ;; Set up babel source-block execution
      (org-babel-do-load-languages
       'org-babel-load-languages
       '((python . t)
         (haskell . t)
         (C . t)
         (js . t)))

      ;; fix org-mode + yasnippet conflicts:
      (add-hook 'org-mode-hook
                (lambda ()
                  (make-variable-buffer-local 'yas/trigger-key)
                  (setq yas/trigger-key [tab])
                  (add-to-list 'org-tab-first-hook 'yas/org-very-safe-expand)
                  (bind-key [tab] 'yas/next-field yas/keymap)))

      ;; Prevent Weird LaTeX class issue
      (unless (boundp 'org-latex-classes)
        (setq org-latex-classes nil))
      (add-to-list 'org-latex-classes
                   '("per-file-class"
                     "\\documentclass{article}
                      [NO-DEFAULT-PACKAGES]
                      [EXTRA]"))

      (defun myorg-update-parent-cookie ()
        (when (equal major-mode 'org-mode)
          (save-excursion
            (ignore-errors
              (org-back-to-heading)
              (org-update-parent-todo-statistics)))))

      (defadvice org-kill-line (after fix-cookies activate)
        (myorg-update-parent-cookie))

      (defadvice kill-whole-line (after fix-cookies activate)
        (myorg-update-parent-cookie))))
#+END_SRC

**** Tips / Tricks
Zero Width Space trick. Use =C-x 8 RET 200b= in between the equal sign to match an org-mode verbatim.
For example: \='quotes'\= will not get highlighted, but \=​'quotes'​\= will.

Use =M-x org-toggle-inline-images= to display linked images in the buffer.
(without a prefix argument, only images without a label are displayed.
With a prefix argument, all images are shown)

*** Markdown
Use [[http://johnmacfarlane.net/pandoc/][Pandoc]]
#+BEGIN_SRC sh
sudo pacman -S cabal-install
cabal upadte
cabal install pandoc
#+END_SRC
Ensure you add =$HOME/.caba./bin= to your path in your profile in order for pandoc to be used

#+BEGIN_SRC emacs-lisp
  (req-package markdown-mode
               :require (pandoc-mode yasnippet)
               :init
               (progn
                 (add-to-list 'auto-mode-alist '("\\.md$" . markdown-mode))
                 (add-to-list 'auto-mode-alist '("\\.markdown$" . markdown-mode))
                 (add-to-list 'auto-mode-alist '("README$" . markdown-mode)))
               :config
               (progn
                 (add-hook 'markdown-mode-hook 'turn-on-pandoc)
                 (add-hook 'pandoc-mode-hook 'pandoc-load-default-settings)
                 (setq markdown-command "pandoc --smart -f markdown -t html5")
                 (setq markdown-css-path (file-truename (concat user-emacs-directory "themes/markdown.css")))
                 (bind-key "C-c h" 'my-markdown-preview-file markdown-mode-map)))

  ;;TODO: set up a save hook to auto-reload the converted markdown on save

  ;; Preview inspired by https://gist.github.com/Javran/9181746

  (defun my-pandoc-markdown-to-html (file-src file-dst)
    "convert markdown files into HTML files."
    (shell-command
     (format "pandoc -s -t html5 %s -o %s" file-src file-dst)))

  (defun my-markdown-preview-file ()
      "generate HTML file for current editing file
      using pandoc, and the open browser to preview
      the resulting HTML file"
      (interactive)
      ;; create place to store the temp HTML file output
      (mkdir "/tmp/markdown_tmps/" t)
      (let* ((dst-dir "/tmp/markdown_tmps/")
             (file-dst
              (concat dst-dir
                      (file-name-base (buffer-file-name))
                      ".html"))
             (url-dst
              (concat "file://" file-dst)))
        (my-pandoc-markdown-to-html (buffer-file-name)
                                 file-dst)
        (split-window-below)
        (other-window 1)
        (eww url-dst)))
#+END_SRC

*** dired+
Dired Plus is an extension to the =dired= file manager in Emacs.
My favorite feature is that pressing =F= will open all marked files.

#+BEGIN_SRC emacs-lisp
(req-package dired+)
#+END_SRC

*** Magit
[[https://github.com/magit/magit][Magit]] is the ultimate =git= interface for Emacs.
#+BEGIN_SRC emacs-lisp
  (req-package magit
               :diminish (magit-auto-revert-mode . "")
               :bind ("C-c g" . magit-status))
#+END_SRC

*** Eshell
Type =clear= to clear the buffer like in other terminal emulators.
#+BEGIN_SRC emacs-lisp
(defun eshell/clear ()
  "04Dec2001 - sailor, to clear the eshell buffer."
  (interactive)
  (let ((inhibit-read-only t))
    (erase-buffer)))
#+END_SRC

*** ERC
Emacs IRC Client
#+BEGIN_SRC emacs-lisp
  (req-package erc
    :config
    (add-hook 'erc-mode-hook 'flyspell-mode))
#+END_SRC

*** JavaScript
js2-mode is full JavaScript AST parser in elisp
#+BEGIN_SRC emacs-lisp
  (req-package js2-mode
               :diminish (js2-mode . "JS2")
               :require (js2-refactor grunt js-comint rainbow-delimiters)
               :bind (("C-M-g" . grunt-exec)
                      ("C-c C-c e" . js-send-last-sexp)
                      ("C-c C-c x" . js-send-last-sexp-and-go)
                      ("C-c C-c b" . js-send-buffer)
                      ("C-c C-c C-b" . js-send-buffer-and-go)
                      ("C-c C-c n" . js-send-region)
                      ("C-c C-c C-n" . js-send-region-and-go)
                      ("C-c C-c l" . js-load-file-and-go))
               :init
               (progn
                 (add-to-list 'auto-mode-alist '("\\.js$" . js2-mode))
                 (add-to-list 'magic-mode-alist '("#!/usr/bin/env node" . js2-mode)))
               :config
               (progn
                 (setq js2-enter-indents-newline nil)
                 (setq js2-bounce-indent-p t)
                 (setq js2-global-externs '("module" "require" "jQuery" "$" "_" "buster" "sinon" "assert" "refute" "setTimeout" "clearTimeout" "setInterval" "clearInterval" "location" "__dirname" "console" "JSON" "process" "setImmediate" "exports" "enum"))

                 ;; Let Flycheck handle errors until js2 mode supports ES6
                 (setq js2-show-parse-errors nil)
                 (setq js2-strict-missing-semi-warning nil)
                 (setq js2-strict-trailing-comma-warning t)

                 (setq js2-basic-offset 2)
                 (setq js-indent-level 2)
                 (setq js2-strict-inconsistent-return-warning nil)
                 (setq js2-include-node-externs t)
                 (setq js2-include-jslint-globals t)
                 (setq js2-indent-ignore-first-tab t)

                 ;; set up js2-refactor map
                 (js2r-add-keybindings-with-prefix "C-c C-r")

                 ;; Set up js-comint for node
                 (setq inferior-js-program-command "node")
                 (setq inferior-js-mode-hook
                       (lambda ()
                         (ansi-color-for-comint-mode-on)
                         (add-to-list
                          'comint-preoutput-filter-functions
                          (lambda (output)
                            (replace-regexp-in-string "\033\\[[0-9]+[A-Z]" "" output)))))

                 ;; Extra configuration that needs to be run on the js2-mode-hook
                 (add-hook 'js2-mode-hook (lambda ()
                                            ;; Rainbows
                                            (rainbow-delimiters-mode)
                                            ;; Electric indent hates bouncies
                                            (electric-indent-mode -1)
                                            ;; Turn on tabs for JavaScript files
                                            ;;TODO: set up folder-local settings for this kind of customization
                                            (setq indent-tabs-mode 1)))))

#+END_SRC

*** JSON
#+BEGIN_SRC emacs-lisp
  (req-package json-mode
               :init
               (add-to-list 'auto-mode-alist '("\\.json$" . json-mode)))
#+END_SRC

*** Handlebars
#+BEGIN_SRC emacs-lisp
  (req-package handlebars-mode
               :init
               (progn
                 (add-to-list 'auto-mode-alist '("\\.hbs$" . handlebars-mode))
                 (add-to-list 'auto-mode-alist '("\\.handlebards$" . handlebars-mode))))
#+END_SRC

*** SVG
#+BEGIN_SRC emacs-lisp
  (req-package image-mode
               :init
               (add-to-list 'auto-mode-alist '("\\.svg$" . image-mode)))
#+END_SRC

*** CoffeeScript
#+BEGIN_SRC emacs-lisp
  (req-package coffee-mode
               :config
               (setq coffee-tab-width 2))
#+END_SRC

*** Fish
#+BEGIN_SRC emacs-lisp
  (req-package fish-mode)
#+END_SRC

* Custom Functions
** Lisp
*** Evaluate and Replace
#+BEGIN_SRC emacs-lisp
(defun eval-and-replace ()
  "Replace the preceding sexp with its value."
  (interactive)
  (backward-kill-sexp)
  (condition-case nil
      (prin1 (eval (read (current-kill 0)))
             (current-buffer))
    (error (message "Invalid expression")
           (insert (current-kill 0)))))
(bind-key "C-x x e" 'eval-and-replace)
#+END_SRC

** Buffer
*** Kill Region / Line
With these in place, you can kill or copy the line point is on with a single keystroke:

- =C-w= kills the current line
- =M-w= copies the current line

Note that if there is an active region, =kill-region= and =kill-ring-save=
will continue to do what they normally do: Kill or copy it.
#+BEGIN_SRC emacs-lisp
  (defadvice kill-region (before slick-cut activate compile)
    "When called interactively with no active region, kill a single
  line instead."
    (interactive
     (if mark-active
         (list (region-beginning) (region-end))
       (list (line-beginning-position) (line-beginning-position 2)))))

  (defadvice kill-ring-save (before slick-copy activate compile)
    "When called interactively with no active region, copy a single
  line instead."
    (interactive
     (if mark-active
         (list (region-beginning) (region-end))
       (message "Copied line")
       (list (line-beginning-position) (line-beginning-position 2)))))
#+END_SRC
Borrowed from [[http://emacs.stackexchange.com/questions/2347/kill-or-copy-current-line-with-minimal-keystrokes][this]] emacs.stackexchange question.

*** Hide Mode Line
Make the mode line disappear.
#+BEGIN_SRC emacs-lisp
;; See http://bzg.fr/emacs-hide-mode-line.html
(defvar-local hidden-mode-line-mode nil)
(defvar-local hide-mode-line nil)

(define-minor-mode hidden-mode-line-mode
  "Minor mode to hide the mode-line in the current buffer."
  :init-value nil
  :global nil
  :variable hidden-mode-line-mode
  :group 'editing-basics
  (if hidden-mode-line-mode
      (setq hide-mode-line mode-line-format
            mode-line-format nil)
    (setq mode-line-format hide-mode-line
          hide-mode-line nil))
  (force-mode-line-update)
  ;; Apparently force-mode-line-update is not always enough to
  ;; redisplay the mode-line
  (redraw-display)
  (when (and (called-interactively-p 'interactive)
             hidden-mode-line-mode)
    (run-with-idle-timer
     0 nil 'message
     (concat "Hidden Mode Line Mode enabled.  "
             "Use M-x hidden-mode-line-mode to make the mode-line appear."))))
  ;; If you want to hide the mode-line in all new buffers
  ;; (add-hook 'after-change-major-mode-hook 'hidden-mode-line-mode))
#+END_SRC

*** Unmark Flyspell
#+BEGIN_SRC emacs-lisp
(defun unmark-flyspell-in-buffer ()
       (interactive)
       (flyspell-delete-all-overlays))
#+END_SRC

*** Dvorak Mode
#+BEGIN_SRC emacs-lisp :tangle no
(defun dvorak-mode()
  "Toggles dvorak input type in the buffer and minibuffer.
   Good for learning Dvorak, or if you really like qwerty bindings."
  (interactive)
  (if (equal current-input-method nil)
      ;; Change buffer to dvorak
      (progn
        ;; Main setup for  all the buffers
        (defadvice switch-to-buffer (after activate-input-method activate)
          (activate-input-method "english-dvorak"))
        (set-input-method "english-dvorak")
        ;; Sets up Dvorak for the minibuffer
        (add-hook 'minibuffer-setup-hook (lambda () (set-input-method "english-dvorak"))))
    ;; Change back to qwerty
    (progn
      ;; Main setup for  all the buffers
      (defadvice switch-to-buffer (after activate-input-method activate)
        (activate-input-method nil))
      (set-input-method nil)
      (remove-hook 'minibuffer-setup-hook (lambda () (set-input-method "english-dvorak"))))))
#+END_SRC

*** Scratch
#+BEGIN_SRC emacs-lisp
(defun create-scratch-buffer nil
  "create a new scratch buffer to work in. (could be *scratch* - *scratchX*)"
  (interactive)
  (let ((n 0)
        bufname)
    (while (progn
             (setq bufname (concat "*scratch"
                                   (if (= n 0) "" (int-to-string n))
                                   "*"))
             (setq n (1+ n))
             (get-buffer bufname)))
    (switch-to-buffer (get-buffer-create bufname))
    (lisp-interaction-mode)))
#+END_SRC

*** Untabify Buffer
#+BEGIN_SRC emacs-lisp
(defun untabify-buffer ()
  (interactive)
  (untabify (point-min) (point-max)))
(bind-key "C-c @ u" 'untabify-buffer)
#+END_SRC

*** Tabify Buffer
#+BEGIN_SRC emacs-lisp
(defun tabify-buffer ()
  (interactive)
  (tabify (point-min) (point-max)))
(bind-key "C-c @ t" 'tabify-buffer)
#+END_SRC

*** Indent Buffer
#+BEGIN_SRC emacs-lisp
(defun indnet-buffer ()
  (interactive)
  (indent-region (point-min) (point-max)))
(bind-key "C-c @ i" 'indent-buffer)
#+END_SRC

*** Cleanup Buffer
#+BEGIN_SRC emacs-lisp
(defun cleanup-buffer ()
  "Perform a bunch of operations on the whitespace content of a buffer.
Including indent-buffer, which should not be called automatically on save."
  (interactive)
  (untabify-buffer)
  (delete-trailing-whitespace)
  (indent-buffer))
#+END_SRC

*** Cleanup Buffer Boring
#+BEGIN_SRC emacs-lisp
(defun cleanup-buffer-boring ()
  "Perform a bunch of operations on the whitespace content of a buffer.
Including indent-buffer, which should not be called automatically on save."
  (interactive)
  (delete-trailing-whitespace))
#+END_SRC

*** Auto Buffer Cleanup
#+BEGIN_SRC emacs-lisp
(defun auto-buffer-cleanup ()
  "Turn on buffer cleanup"
  (interactive)
  (stop-auto-buffer-cleanup)
  (add-hook 'before-save-hook 'cleanup-buffer))
(defun auto-buffer-cleanup-boring ()
  "Turn on buffer cleanup"
  (interactive)
  (stop-auto-buffer-cleanup)
  (add-hook 'before-save-hook 'cleanup-buffer-boring))
(defun stop-auto-buffer-cleanup ()
  "Turn on buffer cleanup"
  (interactive)
  (remove-hook 'before-save-hook 'cleanup-buffer)
  (remove-hook 'before-save-hook 'cleanup-buffer-boring))
(bind-key "C-c @ Y" 'auto-buffer-cleanup)
(bind-key "C-c @ y" 'auto-buffer-cleanup-boring)
(bind-key "C-c @ n" 'stop-auto-buffer-claenup)
(auto-buffer-cleanup-boring)
#+END_SRC

*** Forward Word To Beginning
#+BEGIN_SRC emacs-lisp
;; Mimic vim's "w" command
(defun forward-word-to-beginning (&optional n)
  "Move point forward n words and place cursor at the beginning."
  (interactive "p")
  (let (myword)
    (setq myword
      (if (and transient-mark-mode mark-active)
        (buffer-substring-no-properties (region-beginning) (region-end))
        (thing-at-point 'symbol)))
    (if (not (eq myword nil))
      (forward-word n))
    (forward-word n)
    (backward-word n)))
(bind-key "M-f" 'forward-word-to-beginning)
;; Remap old forward word
(bind-key "M-F" 'forward-word)
#+END_SRC

*** Remove DOS EOL
#+BEGIN_SRC emacs-lisp
;; Hide DOS line endings
(defun remove-dos-eol ()
	(interactive)
	(setq buffer-display-table (make-display-table))
	(aset buffer-display-table ?\^M []))
#+END_SRC

*** Other Window Backwards
#+BEGIN_SRC emacs-lisp
  (defun other-window-backwards (count)
    (itneractive "p")
    (otehr-window (- 0 count)))
  (bind-key "C-x p" 'other-window-backwards)
#+END_SRC

** File
*** Rename Buffer & File
#+BEGIN_SRC emacs-lisp
(defun rename-current-buffer-file ()
  "Renames current buffer and file it is visiting."
  (interactive)
  (let ((name (buffer-name))
        (filename (buffer-file-name)))
    (if (not (and filename (file-exists-p filename)))
        (error "Buffer '%s' is not visiting a file!" name)
      (let ((new-name (read-file-name "New name: " filename)))
        (if (get-buffer new-name)
            (error "A buffer named '%s' already exists!" new-name)
          (rename-file filename new-name 1)
          (rename-buffer new-name)
          (set-visited-file-name new-name)
          (set-buffer-modified-p nil)
          (message "File '%s' successfully renamed to '%s'"
                   name (file-name-nondirectory new-name)))))))
(bind-key "C-c @ r" 'rename-current-buffer-file)
#+END_SRC

*** Delete Buffer & File
#+BEGIN_SRC emacs-lisp
(defun delete-current-buffer-file ()
  "Removes file connected to current buffer and kills buffer."
  (interactive)
  (let ((filename (buffer-file-name))
        (buffer (current-buffer))
        (name (buffer-name)))
    (if (not (and filename (file-exists-p filename)))
        (ido-kill-buffer)
      (when (yes-or-no-p "Are you sure you want to remove this file? ")
        (delete-file filename)
        (kill-buffer buffer)
        (message "File '%s' successfully removed" filename)))))
(bind-key "C-c @ d" 'rename-current-buffer-file)
#+END_SRC

** Miscellaneous
*** Insert Date
#+BEGIN_SRC emacs-lisp
(defun insert-date ()
  "Insert current date yyyy-mm-dd H:M:S."
  (interactive)
  (insert (format-time-string "%Y-%m-%d %T")))
#+END_SRC

** Snippet Helpers
*** JavaScript
#+BEGIN_SRC emacs-lisp
(defun js-method-p ()
  (save-excursion
    (word-search-backward "function")
    (looking-back ": ")))

(defun js-function-declaration-p ()
  (save-excursion
    (word-search-backward "function")
    (looking-back "^\\s *")))

(defun snippet--function-punctuation ()
  (if (js-method-p)
      (when (not (looking-at "[ \n\t\r]*[},]"))
        (insert ","))
    (unless (js-function-declaration-p)
      (if (looking-at "$") (insert ";")))))

(defun snippet--function-name ()
  (if (js-function-declaration-p) "name" ""))
#+END_SRC

*** Other
#+BEGIN_SRC emacs-lisp
;;; clojure
(defun snippet--clojure-namespace-from-buffer-file-name ()
  (replace-regexp-in-string "_" "-"
   (replace-regexp-in-string "/" "."
    (chop-prefix "test/"
    (chop-prefix "src/"
    (chop-suffix ".clj"
     (substring (buffer-file-name) (length eproject-root))))))))

(defun snippet--clojure-namespace-under-test ()
  (replace-regexp-in-string "-test" "" (snippet--clojure-namespace-from-buffer-file-name)))

;; snippet-helper-helpers
(defun chop-suffix (suffix s)
  "Remove string 'suffix' if it is at end of string 's'"
  (let ((pos (- (length suffix))))
    (if (and (>= (length s) (length suffix))
             (string= suffix (substring s pos)))
        (substring s 0 pos)
      s)))

(defun chop-prefix (prefix s)
  "Remove string 'prefix' if it is at start of string 's'"
  (let ((pos (length prefix)))
    (if (and (>= (length s) (length prefix))
             (string= prefix (substring s 0 pos)))
        (substring s pos)
      s)))
#+END_SRC

* Games
Emacs is fun.

*** Built in Games
=M-x <game>= to play.
- Snake: Eat the red squares.
- Tetris: Arrange falling blocks.
- Pong: Two-Player ping-pong.
- Zone: Manipulates the text in your buffer when Emacs is idle.
- Life: Watch a Conway's Game of Life simulation.
- Morse Code: Transate a region into dots and dashes.
- 2048: Merge teh tiles to reach 2048

* Server
** Client/Server
Running emacs as greatly improves startup
#+BEGIN_SRC emacs-lisp
  (req-package server
               :config
               (unless (server-running-p)
                 (server-start)))
#+END_SRC

** Edit With Emacs
[[https://chrome.google.com/webstore/detail/edit-with-emacs/ljobjlafonikaiipfkggjbhkghgicgoh?hl=en][Edit With Emacs]] provides a method to use an edit server for text fields in the browser.
#+BEGIN_SRC emacs-lisp
  (req-package edit-server
               :config
               (when (daemonp)
                 (edit-server-start)))
#+END_SRC

* Finish Requirements
All done with  =req-package=.
#+BEGIN_SRC emacs-lisp
(req-package-finish)
#+END_SRC
