(deftheme sane-smyx
  "Created 2014-10-06.")

(custom-theme-set-faces
 'sane-smyx
 '(cursor ((t (:background "#F7F7F7"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#E1Fa81" :background "#282828"))))
 '(highlight ((t (:background "#333333"))))
 '(region ((t (:background "#5F5F5F"))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((t (:background "#484848"))))
 '(trailing-whitespace ((t (:background "#FAB1AB"))))
 '(font-lock-builtin-face ((t (:foreground "#FFA600"))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:slant italic :foreground "#d3d3d3"))))
 '(font-lock-constant-face ((t (:foreground "#FAB1AB"))))
 '(font-lock-doc-face ((t (:inherit (font-lock-string-face)))))
 '(font-lock-function-name-face ((t (:foreground "#96D9F1"))))
 '(font-lock-keyword-face ((t (:foreground "#D1FA71"))))
 '(font-lock-negation-char-face ((t (:foreground "#FAB1AB"))))
 '(font-lock-preprocessor-face ((t (:foreground "#919191" :inherit (font-lock-builtin-face)))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#F6DC69" :inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#FAB1AB" :inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#F6DC69"))))
 '(font-lock-type-face ((t (:foreground "#96D9F1"))))
 '(font-lock-variable-name-face ((t (:foreground "#96D9F1"))))
 '(font-lock-warning-face ((t (:foreground "#EBA9F7" :inherit (error)))))
 '(button ((t (:underline (:color foreground-color :style line) :inherit (link)))))
 '(link ((t (:weight bold :underline (:color foreground-color :style line) :foreground "#F6DC69"))))
 '(link-visited ((t (:weight normal :underline (:color foreground-color :style line) :foreground "#d0bf8f" :inherit (link)))))
 '(fringe ((((class color) (background light)) (:background "grey95")) (((class color) (background dark)) (:background "grey10")) (t (:background "gray"))))
 '(header-line ((t (:box (:line-width -1 :color nil :style released-button) :foreground "#F6DC69" :background "#202020" :inherit (mode-line)))))
 '(tooltip ((((class color)) (:inherit (variable-pitch) :foreground "black" :background "lightyellow")) (t (:inherit (variable-pitch)))))
 '(mode-line ((t (:box (:line-width -1 :color nil :style released-button) :foreground "#96D9F1" :background "#353535"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:weight light :box (:line-width -1 :color "#96D9F1" :style nil) :foreground "#4D4D4D" :background "#1A1A1A" :inherit (mode-line)))))
 '(isearch ((t (:foreground "#282828" :background "#D1FA71"))))
 '(isearch-fail ((t (:foreground "#282828" :background "#EBA9F7"))))
 '(lazy-highlight ((t (:foreground "#282828" :background "#F6DC69"))))
 '(match ((t (:foreground "#DB98E7" :background "#282828"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:background "#333333" :inherit (isearch)))))
 '(default ((t (:family "DejaVu Sans Mono" :foundry "unknown" :width normal :height 90 :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#F7F7F7" :background "#282828" :stipple nil :inherit nil)))))

(provide-theme 'sane-smyx)
